version: "3.9"
services:
  api:
    build: ./docker
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/api

  mysql:
    image: mysql:8
    env_file: ./docker/mysql-env
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tmpfs:
      - /tmp

volumes:
    mysql-data: